### DISCUSSION TITLE
Team view across different repositories?

### DISCUSSION THREAD

**Discussion by 3pilef** [flowwer-dev/pull-request-stats#51] [Q&A] [answered]
Manuel, thanks a lot for this awesome nifty tool.

Is there a way to consolidate stats across different repositories (not necessarily all of an organization but a certain set of repositories across the org)?

**Comment by manuelmhtr** [comment, marked as answer]
Hi @3pilef, thanks for your comments!

Yes, you can use the `repositories` option instead of `organization` and send a comma-separated list of the repositories you need. 

For example:

```yml
name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: 'celonis/repo1,celonis/repo2,celonis/repo3'
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
```

> ⚠️ Notice you also need to pass personal access token since the default one has only permissions for the current repo.

The only problem is you can't post multiple stats tables in the same repo. You'd need to configure each group of stats across multiple repositories.

Please tell me if this work for you or there's something further I can help with.
