### DISCUSSION TITLE
Is any way to run this project against a local setup instead of storing information within https://app.flowwer.dev/?

### DISCUSSION THREAD

**Discussion by eduardoacskimlinks** [flowwer-dev/pull-request-stats#80] [Q&A]
I love this project, but we are concerned about exposing data through workflow to your website. Will it be possible to have a similar workflow without generating external charts? Or exposing data externally?

**Comment by manuelmhtr** [comment]
Hi @eduardoacskimlinks
Yes, it's possible to disable external charts using the option `disableLinks`. For example:

```yml
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          organization: 'piedpiper'
          disableLinks: true
```

Also, it's important to say **no data** is stored in `https://app.flowwer.dev/`. If you inspect the generated links, all the information required to print the charts is generated "locally" in the Github action and encoded in the link using [jsurl](https://www.npmjs.com/package/jsurl). You can event play with the URL and see how charts change.

Best,
