### ISSUE TITLE
Personal token displayed in JSON output

### ISSUE THREAD

**Issue by alopexplenus** [flowwer-dev/pull-request-stats#100]
I used the workflow in a simple setting like this:

```yml
jobs:
  getprs:
    runs-on: self-hosted-std
    # Expose step outputs as job outputs
    outputs:
      prstats: ${{ steps.prs.outputs.resultsJson }}

    steps:
      - name: prs
        id: prs
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.PAT }}
          repositories: "smb-ag/${{ github.event.inputs.repo }}"
          disableLinks: true
          sortBy: 'COMMENTS'
          publishAs: 'NONE'
```

and discovered that the Access tokens are displayed in the JSON output, which was unexpected behaviour

```JSON
{
"currentRepo":"my/repo",
"githubToken":"Oh NO!",
"personalToken":"Oh NO!"
...
}
```
