### ISSUE TITLE
Action failing with error `Error fetching pull requests with variables...`

### ISSUE THREAD

**Issue by mskwon1** [flowwer-dev/pull-request-stats#103]
First, thanks for the great tool. love how easy it is to use & how useful the results are!

I have created a yml file to run this action monthly, just like below

```yml
name: 월간 코드리뷰 통계

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  send-code-review-stat-to-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@main
        with:
          period: 30
          token: MASKED(uses secret)
          repositories: 'MASKED'
          stats: 'totalReviews,timeToReview,totalComments,commentsPerReview,reviewedLines,openedPullRequests,reviewedLines'
          webhook: 'MASKED'
```

however it is failing even if i have tried it multiple times with errors below

```
Error fetching pull requests with variables "{"search":"type:pr sort:author-date repo:MASKED created:>=2025-03-02T02:26:07.892Z","limit":100}". Error: HttpError: We couldn't respond to your request in time. Sorry about that. Please try resubmitting your request and contact us if the problem persists.
```

```
Error fetching pull requests with variables "{"search":"type:pr sort:author-date repo:MASKED created:>=2025-03-02T04:07:34.748Z","limit":100}". Error: HttpError: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query on 2025-04-01T04:07:45+00:00. This may be the result of a timeout, or it could be a GitHub bug. Please include `0501:183DE6:3FA7A52:7F226E7:67EB6686` when reporting this issue."}]}
```

Any hints or guesses? thanks in advance
it might be a problem with github.. but i don't know how i could solve this 🤔
