### ISSUE TITLE
Unable to see users and data after successful run of action

### ISSUE THREAD

**Issue by pantheman1** [flowwer-dev/pull-request-stats#19]
Hello,

I have implemented this Github action but it doesn't appear to access any of the user or PR data in the repos. Can you help me understand what might be wrong? Here is the code:

```
---
name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.PR_REPORT_GITHUB_PERSONAL_ACCESS_TOKEN }}
          organization: 'Vivpro'
          period: 30
          charts: true
          disable-links: true
          sort-by: 'TIME'
          limit: 0
```

The job runs successfully. Here is the output I see in the description:
![image](https://user-images.githubusercontent.com/71561333/147615037-b1b0ba1f-0d90-49e7-909f-2d92879b94dc.png)

For some added information, I created a new repo where this workflow lives.

Inside the `with`, I also tried adding `repositories: comma separated list of our repositories` but that hasn't worked either.

Thanks so much in advance for helping!
