### ISSUE TITLE
Feature: Allow Posting it as Comment

### ISSUE THREAD

**Issue by rowi1de** [flowwer-dev/pull-request-stats#24]
Please add a feature that allows switching from Description to Comment.

```yaml

   
name: Pull Request Stats

on: 
  pull_request:
    types: [opened]
  

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          comment: true # set trigger accordingly, default is opened, synchronize, and reopened
```
