### ISSUE TITLE
Error `Parameter token or opts.auth is required`

### ISSUE THREAD

**Issue by WaKeMaTTa** [flowwer-dev/pull-request-stats#35]
Hello, sometimes we get randomly the following error:

```
Parameter token or opts.auth is required
```

any idea why?

**Comment by manuelmhtr** [comment]
Hi @WaKeMaTTa, I've reviewed the problem and it seems to occur when for some reason the `token` parameter is empty.

I'm not sure about the reason. Some people got the [error](https://github.com/contributor-assistant/github-action/issues/55) running the action with the `pull_request_target` trigger (from a forked repo).

[Others] solve it by declaring the Github token in the repo secrets rather than from the organization's.

Is any of these your case?

If not, could you share the configuration you are using?

**Comment by WaKeMaTTa** [comment]
This is our current configuration:

```yml
name: Pull Request Stats

on: pull_request

jobs:
  pull-request-stats-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Stats
        uses: flowwer-dev/pull-request-stats@v2.3.1
        with:
          token: ${{ secrets.PULL_REQUEST_STATS_TOKEN }}
          organization: wecasa
          charts: true
          period: 10
```

`${{ secrets.PULL_REQUEST_STATS_TOKEN }}` is configured at Organization level.

Ok, then we will move it to the repo settings.
