### ISSUE TITLE
Error only when Scheduled run: Cannot read property 'full_name' of undefined

### ISSUE THREAD

**Issue by pattwell** [flowwer-dev/pull-request-stats#44]
Hello, I am not sure this isn't just me doing something wrong, but I get the following error only when the action is _not_ triggered manually:
`Cannot read property 'full_name' of undefined`

![Screenshot 2022-08-01 at 11 34 52](https://user-images.githubusercontent.com/75476610/182130359-7b7f5309-8790-4159-9059-b7f86682b86d.png)

The code is as below: 

```
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 1' # Weekly on Mondays at 7am

jobs:
  stats:
    name: Send PR Stats to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Backend Stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: <redacted>
          limit: 10
          token: ${{ secrets.REVIEW_BOT_READONLY_PAT }}
          slack-webhook: ${{ secrets.PR_STATS_SLACK_WEBHOOK_URL }}
          slack-channel: '<redacted>'
```

When I run it manually it works, so this error only comes up when it is running based on the cron.  I'm not sure if it's something to do with it not having the right context of the current repo perhaps?

Any advice appreciated :)
