### ISSUE TITLE
Stats not aggregated across the repositories

### ISSUE THREAD

**Issue by tgrk** [flowwer-dev/pull-request-stats#45]
Hello, I am having an issue using the `repositories` feature (or I misunderstood it). I am using the following config (`GITHUB_API_TOKEN` has rights to read repo information and is a member of all the listed repositories), and PR stats are always calculated only for the current repository.

Configuration
```yaml
...
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GITHUB_API_TOKEN }}
          repositories: 'repo/foo,repo/bar'
          charts: true
          sort-by: 'REVIEWS'
          period: 14
```

Do you have any suggestions on how to enable cross repository stats?

Cheers,
Martin
