### ISSUE TITLE
Dependabot PRs trigger GraphQL errors in job

### ISSUE THREAD

**Issue by eddie-dunn** [flowwer-dev/pull-request-stats#47]
We've enabled dependabot for our repo. Whenever it creates a PR to update a dependency, the default job fails with the following error:

```
Error: GraphqlResponseError: Request failed due to following response errors:
 - Resource not accessible by integration
```

<details>
<summary>.github/workflows/pr_stats.yml</summary>

```
name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 60
          charts: true
          sort-by: "TIME"
```

</details>

**Comment by manuelmhtr** [comment]
Hi @eddie-dunn,
It looks like there's something related with the GITHUB_TOKEN in the action. There are some [recommendations here](https://stackoverflow.com/a/70448851/1628009) that might be useful:
* Add `permissions: write-all` setting on the job.
* Create a personal access token.

Another solution is to ignore this action from depedabot's PRs:
```yml
name: Pull Request Stats

on:
  pull_request:
    types: [opened]
    branches-ignore:    
      - 'dependabot/**'
```
