### ISSUE TITLE
Sort-by-time doesn't seem to work properly

### ISSUE THREAD

**Issue by zachliu** [flowwer-dev/pull-request-stats#71]
I have this in my workflow ():

```yaml
  #########################################################
  # Show PR statistics
  # #######################################################
  stats:
    name: Obtain PR stats
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          organization: '<my-org>'
          period: 30
          charts: true
          sort-by: 'TIME'
```

what i got

![pr-stats-sort-by-time](https://github.com/flowwer-dev/pull-request-stats/assets/14293802/58fb4637-f076-4b04-a519-296a65664f4f)
