### ISSUE TITLE
Error fetching pull requests with id

### ISSUE THREAD

**Issue by xdays** [flowwer-dev/pull-request-stats#8]
Here's my worflow yaml:

```
name: stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.GHB_PAT }}
          charts: true
          disable-links: true
          sort-by: 'COMMENTS'

```

Just get the error:

```
Error: Error fetching pull requests with id "MDExOlB1bGxSZXF1xxxxx". Error: GraphqlError: Could not resolve to a node with the global id of 'MDExOlB1bGxSZXF1xxxxx'
```

Thanks
